### PR TITLE
add post - audio production

### PR DESCRIPTION
**Pull request by EdWarga**

### CODE REVIEW

**Comment by EdWarga** [comment]
merged this pull request so I have page available for workshop tomorrow.

**Comment by EdWarga** [comment]
Something's not working :(
This new post is not displaying on the website. @CliffordAnderson, could you help troubleshoot?

**Comment by CliffordAnderson** [comment]
Yes, the timestamp is the problem. The post will not appear until the date is reached. I've changed it to today and it shows up.

**Comment by EdWarga** [comment]
Thanks Cliff!

Sent from my iPhone

On Feb 4, 2016, at 6:58 PM, Clifford Anderson <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, the timestamp is the problem. The post will not appear until the date is reached. I've changed it to today and it shows up.

**Pull request merged**
